version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:12.10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=postgres
      - APP_DB_NAME=weather
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE=${DATABASE}
    ports:
      - 4000:80
    external_links:
      - postgres
    depends_on:
      - postgres
